# Generated by Django 3.2.4 on 2021-06-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='slug',
        ),
    ]
